"""initial clean state

Revision ID: b6dc2ca213cb
Revises: 
Create Date: 2025-04-05 16:11:05.604034

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b6dc2ca213cb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('active_players',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nickname', sa.String(length=100), nullable=False),
    sa.Column('moved_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('active_players', schema=None) as batch_op:
        batch_op.create_index('idx_active_players_nickname_moved', ['nickname', 'moved_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_active_players_moved_at'), ['moved_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_active_players_nickname'), ['nickname'], unique=False)

    op.create_table('completed_players',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nickname', sa.String(length=50), nullable=False),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('games_played', sa.Integer(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('completed_players', schema=None) as batch_op:
        batch_op.create_index('idx_completed_players_nickname_rating', ['nickname', 'rating'], unique=False)
        batch_op.create_index(batch_op.f('ix_completed_players_completed_at'), ['completed_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_completed_players_games_played'), ['games_played'], unique=False)
        batch_op.create_index(batch_op.f('ix_completed_players_nickname'), ['nickname'], unique=False)
        batch_op.create_index(batch_op.f('ix_completed_players_rating'), ['rating'], unique=False)

    op.create_table('queue',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nickname', sa.String(length=100), nullable=False),
    sa.Column('joined_at', sa.DateTime(), nullable=True),
    sa.Column('last_joined_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('queue', schema=None) as batch_op:
        batch_op.create_index('idx_queue_nickname_joined', ['nickname', 'joined_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_queue_joined_at'), ['joined_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_queue_last_joined_at'), ['last_joined_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_queue_nickname'), ['nickname'], unique=False)

    op.create_table('song_orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_code', sa.String(length=10), nullable=False),
    sa.Column('nickname', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(), nullable=True),
    sa.Column('youtube_url', sa.String(length=255), nullable=True),
    sa.Column('song_title', sa.String(length=255), nullable=True),
    sa.Column('artist', sa.String(length=255), nullable=True),
    sa.Column('played', sa.Boolean(), nullable=True),
    sa.Column('played_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('song_orders', schema=None) as batch_op:
        batch_op.create_index('idx_song_order_status_created', ['status', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_song_orders_confirmed_at'), ['confirmed_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_song_orders_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_song_orders_nickname'), ['nickname'], unique=False)
        batch_op.create_index(batch_op.f('ix_song_orders_order_code'), ['order_code'], unique=True)
        batch_op.create_index(batch_op.f('ix_song_orders_played'), ['played'], unique=False)
        batch_op.create_index(batch_op.f('ix_song_orders_played_at'), ['played_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_song_orders_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_song_orders_youtube_url'), ['youtube_url'], unique=False)

    op.create_table('songs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('youtube_url', sa.String(length=255), nullable=False),
    sa.Column('added_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('songs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_songs_added_at'), ['added_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_songs_youtube_url'), ['youtube_url'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('songs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_songs_youtube_url'))
        batch_op.drop_index(batch_op.f('ix_songs_added_at'))

    op.drop_table('songs')
    with op.batch_alter_table('song_orders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_song_orders_youtube_url'))
        batch_op.drop_index(batch_op.f('ix_song_orders_status'))
        batch_op.drop_index(batch_op.f('ix_song_orders_played_at'))
        batch_op.drop_index(batch_op.f('ix_song_orders_played'))
        batch_op.drop_index(batch_op.f('ix_song_orders_order_code'))
        batch_op.drop_index(batch_op.f('ix_song_orders_nickname'))
        batch_op.drop_index(batch_op.f('ix_song_orders_created_at'))
        batch_op.drop_index(batch_op.f('ix_song_orders_confirmed_at'))
        batch_op.drop_index('idx_song_order_status_created')

    op.drop_table('song_orders')
    with op.batch_alter_table('queue', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_queue_nickname'))
        batch_op.drop_index(batch_op.f('ix_queue_last_joined_at'))
        batch_op.drop_index(batch_op.f('ix_queue_joined_at'))
        batch_op.drop_index('idx_queue_nickname_joined')

    op.drop_table('queue')
    with op.batch_alter_table('completed_players', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_completed_players_rating'))
        batch_op.drop_index(batch_op.f('ix_completed_players_nickname'))
        batch_op.drop_index(batch_op.f('ix_completed_players_games_played'))
        batch_op.drop_index(batch_op.f('ix_completed_players_completed_at'))
        batch_op.drop_index('idx_completed_players_nickname_rating')

    op.drop_table('completed_players')
    with op.batch_alter_table('active_players', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_active_players_nickname'))
        batch_op.drop_index(batch_op.f('ix_active_players_moved_at'))
        batch_op.drop_index('idx_active_players_nickname_moved')

    op.drop_table('active_players')
    # ### end Alembic commands ###
