"""Add rating to CompletedPlayers

Revision ID: f8671027bb85
Revises: 78b883e6e15b
Create Date: 2025-03-23 13:10:34.294902

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f8671027bb85'
down_revision = '78b883e6e15b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('completed_players', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rating', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('completed_players', schema=None) as batch_op:
        batch_op.drop_column('rating')

    # ### end Alembic commands ###
